import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            colors: {
                'outline-variant': '#aeadac',
                'inverse-primary': '#84fb42',
                'surface-container-lowest': '#ffffff',
                'primary': '#2a6900',
                'on-background': '#2e2f2f',
                'surface-container-highest': '#dedcdc',
                'on-tertiary-container': '#574300',
                'inverse-surface': '#0e0e0e',
                'surface-container-high': '#e4e2e2',
                'on-primary-fixed': '#1a4700',
                'error': '#b02500',
                'on-surface': '#2e2f2f',
                'surface-container': '#e9e8e7',
                'secondary-fixed-dim': '#80ccff',
                'tertiary-fixed-dim': '#edba00',
                'on-primary-container': '#245c00',
                'on-secondary-container': '#004c6e',
                'primary-fixed-dim': '#76ec33',
                'on-secondary-fixed-variant': '#00567c',
                'tertiary-dim': '#644c00',
                'on-surface-variant': '#5c5b5b',
                'on-error': '#ffefec',
                'surface-container-low': '#f2f0f0',
                'surface-bright': '#f8f6f5',
                'primary-container': '#84fb42',
                'on-tertiary-fixed-variant': '#634c00',
                'inverse-on-surface': '#9e9d9c',
                'on-primary-fixed-variant': '#296700',
                'on-primary': '#d5ffb9',
                'on-error-container': '#520c00',
                'secondary': '#00628c',
                'outline': '#777776',
                'on-secondary-fixed': '#003852',
                'primary-fixed': '#84fb42',
                'primary-dim': '#235b00',
                'tertiary': '#725800',
                'surface-variant': '#dedcdc',
                'error-container': '#f95630',
                'surface-tint': '#2a6900',
                'secondary-fixed': '#a3d8ff',
                'secondary-dim': '#00557a',
                'on-tertiary': '#fff1d7',
                'tertiary-container': '#fec700',
                'tertiary-fixed': '#fec700',
                'secondary-container': '#a3d8ff',
                'on-tertiary-fixed': '#403000',
                'surface-dim': '#d5d4d4',
                'surface': '#f8f6f5',
                'background': '#f8f6f5',
                'on-secondary': '#e9f4ff',
                'error-dim': '#b92902',
            },
            borderRadius: {
                'DEFAULT': '1rem',
                'lg': '2rem',
                'xl': '3rem',
                'full': '9999px',
            },
            fontFamily: {
                sans: ['Be Vietnam Pro', ...defaultTheme.fontFamily.sans],
                headline: ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
                display: ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
                body: ['Be Vietnam Pro', ...defaultTheme.fontFamily.sans],
                label: ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
            },
        },
    },

    plugins: [forms],
};
